import { client } from '@/sanity/lib/client';
import Head from 'next/head';
import Image from 'next/image';

export default async function Studio() {
  const res = await client.fetch("*[_type == 'landingPage'][0].sections[3]{'studioImg' : studioImg.asset->url,'studioBtnText' : studioBtnText,'studioHeading' : studioHeading,'studioPara' : studioPara, 'studioSecPara' : studioSecPara}")
  const {studioHeading, studioImg, studioBtnText, studioPara, studioSecPara } = await res
  return (
    <div className="max-w-[1440px] h-auto">
      <Head>
        <title>Avion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow">
        <div className="flex flex-col md:flex-row items-center gap-0 bg-white">
          {/* Text Section */}
          <div className="w-full md:w-1/2 p-6 md:p-10">
            <h1 className="text-3xl text-[#2A254B]">
              {studioHeading}
            </h1>
            <p className="mt-4 text-[#2A254B]">
              {studioPara }
            </p>
            <p className="mt-4 text-[#2A254B]">
            {studioSecPara}
            </p>
            <button className="mt-8 bg-gray-100 hover:bg-gray-700 text-[#2A254B] py-2 px-4 rounded focus:outline-none focus:shadow-outline">
              {studioBtnText}
            </button>
          </div>

          {/* Image Section */}
          <div className="w-full md:w-1/2 h-auto">
            <Image
              src={studioImg}
              alt="Avion Furniture"
              width={720}
              height={603}
              className="w-full h-full object-cover"
            />
          </div>
        </div>
        
      </main>
    </div>
  );
}
